

services:
  postgres:
    image: postgres:16
    container_name: euro_adoption_postgres
    restart: unless-stopped

    ports:
      - "5433:5432"

    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: euro_tracker

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
